### 卷积

In [1]:
import numpy as np

inputD = np.array(
         [[245, 253, 24, 255, 255, 255],
         [255, 255, 17, 241, 245, 247],
         [249, 255, 25, 247, 255, 255],
         [255, 255, 55, 238, 171, 184],
         [254, 248, 31, 172, 87, 254],
         [255, 249, 15, 231, 87, 187]])

inputD2 = np.array([[0, 0, 0, 0, 0, 0, 0, 0],
         [0, 245, 253, 24, 255, 255, 255, 0],
         [0, 255, 255, 17, 241, 245, 247, 0],
         [0, 249, 255, 25, 247, 255, 255, 0],
         [0, 255, 255, 55, 238, 171, 184, 0],
         [0, 254, 248, 31, 172, 87, 254, 0],
         [0, 255, 249, 15, 231, 87, 187, 0],
         [0, 0, 0, 0, 0, 0, 0, 0]])

weight = np.array(
          [[1, 0, -1],
          [1, 0, -1],
          [1, 0, -1]])

weight2 = np.array(
          [[1, 1, 1],
          [0, 0, 0],
          [-1, -1, -1]])

In [2]:
def conv(f, kernel):
    [h, w] = f.shape # h=6, w=6
    [k, _] = kernel.shape # k=3
    convR = np.zeros([h-k+1, w-k+1])
    for i in range(h-k+1):
        for j in range(w-k+1):
            inputDi = f[i:i+k,j:j+k]
            convR[i][j] = min(abs(np.sum(kernel*inputDi)),255)
    return convR

In [3]:
def conv2(f, kernel):
    [h, w] = f.shape # h=6, w=6
    [k, _] = kernel.shape # k=3
    convR = np.zeros([h-k+1, w-k+1])
    for i in range(h-k+1):
        for j in range(w-k+1):
            inputDi = f[i:i+k,j:j+k]
            convR[i][j] = np.sum(kernel*inputDi)
    return convR

In [4]:
if __name__ == '__main__':
    result = conv(inputD, weight)
    result2 = conv(inputD, weight2)
    print(result)
    print(result2)

[[255.  20. 255.  14.]
 [255.  39. 255.  40.]
 [255. 101. 255.  36.]
 [255. 111. 244.  16.]]
[[  7.   5.   7.   8.]
 [ 38.  35.  39. 140.]
 [  4.  76. 237. 244.]
 [ 46.  53. 131.  88.]]


In [5]:
result3 = conv2(inputD, weight)
result4 = conv2(inputD, weight2)
print(result3)
print(result4)

[[ 683.   20. -689.  -14.]
 [ 662.   39. -574.   40.]
 [ 647.  101. -402.  -36.]
 [ 663.  111. -244.   16.]]
[[ -7.   5.   7.   8.]
 [-38. -35.  39. 140.]
 [ -4.  76. 237. 244.]
 [ 46.  53. 131.  88.]]


In [6]:
result5 = conv(inputD2, weight)
result6 = conv(inputD2, weight2)
print(result5)
print(result6)

[[255. 255.  12. 255.   6. 255.]
 [255. 255.  20. 255.  14. 255.]
 [255. 255.  39. 255.  40. 255.]
 [255. 255. 101. 255.  36. 255.]
 [255. 255. 111. 244.  16. 255.]
 [255. 255.  94. 128.  38. 174.]]
[[255. 255. 255. 255. 255. 255.]
 [  6.   7.   5.   7.   8.   0.]
 [  0.  38.  35.  39. 140. 137.]
 [  2.   4.  76. 237. 244. 169.]
 [  6.  46.  53. 131.  88.  81.]
 [255. 255. 255. 255. 255. 255.]]


In [1]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

# we want to set the figure size to 128*128
num_px = 128
image = Image.open('./fig/cat.jpg').resize(size=(num_px,num_px)) # change this to the name of your image file 
image1 = np.array(image).reshape((1, num_px*num_px*3)).T  # (49152, 1)

print(image1)
image.show()

[[ 86]
 [ 18]
 [  7]
 ...
 [159]
 [ 99]
 [ 63]]
